### ISSUE TITLE
SVG/Fill render black squares on macOS

### ISSUE THREAD

**Issue by KodaKoder** [linebender/vello#154] opened 2022-02-25 01:50 UTC
I'm trying to render the tiger SVG on macOS/Metal and I get some strange result
also some black square appears inside rect fills

is this due to metal api? 
there is a way to use Vulkan/MoltenVK to render on `macOS?`

Thanks
<img width="1136" alt="IMG_3524" src="https://user-images.githubusercontent.com/771226/155639391-1bbe0820-b155-44df-acdf-6a9420301b47.png">
<img width="1136" alt="IMG_8823" src="https://user-images.githubusercontent.com/771226/155639412-7b3cb722-cd13-44ac-a531-bdd025b6f5c5.png">
<img width="271" alt="IMG_0038" src="https://user-images.githubusercontent.com/771226/155639422-603d14b9-a09b-4072-a67f-695e20ea01ae.png">

**Comment by raphlinus** [comment] 2022-02-25 02:00
Can you give a little more detail about your macOS environment? I'm using an M1 as my daily driver and haven't seen this. I do have access to other hardware though.

Obviously it's hard to say what the problem is without digging, but I'd be suspicious of the shader translation in spirv-cross, which is the same as what it would be in MoltenVK. It should in theory be possible to compile the Vulkan version on mac, but it's very unlikely it will solve this problem.

Does forcing the `session.gpu_info().workgroup_limits.max_invocations >= 1024` predicate in [piet-gpu/src/lib.rs](https://github.com/linebender/piet-gpu/blob/d81e5cb4ee145abd1f2f01904579cb3f93960e97/piet-gpu/src/lib.rs#L225) to false help? If so, I think I know what it is.

**Comment by KodaKoder** [comment] 2022-02-25 02:20
Hello 
thanks for your help
I tried something like        
"if session.gpu_info().workgroup_limits.max_invocations >= 1024 && false" but did not change the result

I attach some samples on different devices
![IMG_4736](https://user-images.githubusercontent.com/771226/155641242-d85d032e-fd56-400f-a755-ca3104ebc5e3.jpeg)

![IMG_9321](https://user-images.githubusercontent.com/771226/155641272-f832bae0-3ae6-46df-9929-4b15393fd1ba.jpeg)

![PNG image](https://user-images.githubusercontent.com/771226/155641288-e35ab722-509b-41f2-8fc9-cfa5069b0c1b.jpeg)

**Comment by raphlinus** [comment] 2022-02-25 02:36
Thanks for the report, I will investigate. I am able to repro the inverted colors on my M1 :). GPU portability is hard.

**Comment by KodaKoder** [comment] 2022-02-25 02:44
If you need more informations or
I can help you in any way just tell me

**Comment by DJMcNab** [comment] 2023-02-11 14:25
Since #193 , we've moved over to using `wgpu`. Can this still be reproduced?

**Comment by raphlinus** [comment] 2023-05-25 14:14
A lot has changed since this issue was filed and we're not seeing similar things now, so closing. Thanks for the report!

**Closed by raphlinus** 2023-05-25 14:14 UTC
