### ISSUE TITLE
Corruption issue with clipping

### ISSUE THREAD

**Issue by nicoburns** [linebender/vello#644] opened 2024-07-26 01:12 UTC
The output rendered by Vello is sometimes corrupted when using clips such as:

```rust
scene.push_layer(Mix::Clip, 1.0, transform, &clip);
scene.pop_layer()
```

This occurs:
- With or without anything being drawn in the clipped layer
- With only small numbers of clips (see below for an example with only 3)
- With no clip nesting (although the example below might nest - not sure)
- With various different blend modes (`Blendmode::default()` and `Mix::Normal` both also exhibit this behaviour)
- With various transform/clip shapes (these do appear to sometimes affect the nature/position of the corruption)

## Runnable example

The `vello-clip-bug` branch of Blitz (https://github.com/DioxusLabs/blitz/tree/vello-clip-bug) reproduces this with `cargo run --release --example google` (also reproduces in debug mode). I think this is the best repro because it happens with only 3 clips (assuming my counting is correct). Vello-related code is almost all in `packages/blitz/src` (and there isn't much else in that dir). The vello setup code is in `renderer.rs`. The vello scene creation code is in `renderer/render.rs`.

There is a suspicion that this could be caused by overlapping clips: https://xi.zulipchat.com/#narrow/stream/197075-gpu/topic/Vello.3A.20.60push_layer.60.20causing.20black.20rectangle

## Screenshots

The issue causes corruption like the following:

<img width="912" alt="Screenshot 2024-07-25 at 20 59 55" src="https://github.com/user-attachments/assets/2ce0ad32-5a8f-4d76-806d-d476a3e0fd65">

It is supposed to look like:

<img width="912" alt="Screenshot 2024-07-26 at 13 06 06" src="https://github.com/user-attachments/assets/9965b612-4842-47b4-85af-a408eeb721c7">

**Comment by raphlinus** [comment] 2024-07-31 20:00
I've done some investigation on this. I believe the main culprit is the zero-size clip that's being pushed - if I tweak the code so the width is at least 1e-3 (instead of 0), then the rendering is as intended.

To be clear, that is a bug in Vello and should be fixed. But it also suggests a workaround.

Other findings: use_cpu makes no difference, and it's not an issue with the blend stack size - that said, I think we should prioritize that last soon, as it's likely we'll run into it as applications use deeply nested clips.

**Comment by nicoburns** [comment] 2024-07-31 21:06
Ah, that seems good if it's just the zero-sized clips. Easy to workaround, and I'd guess easy to fix. Regarding the "blend stack size", do we have a clear idea of what the limits currently are? If we do, then I should be able to enable clipping in Blitz with guards to prevent the limits being exceeded.

**Comment by raphlinus** [comment] 2024-07-31 21:06
Also, a very simple repro: the example in #649 but with one of the rect sizes set to zero renders with an entirely black canvas.

I've done some more digging and have a pretty good idea what's going on. There's [logic](https://github.com/linebender/vello/blob/9c29a4f29f2aef58ed7ba45ee2fac35d3f7875eb/vello/src/scene.rs#L80) in `push_layer` to detect an invalid (empty, basically) path and push a valid but empty path in its place. However, the path encoding logic is pretty aggressive in suppressing zero-length segments, so as a result there's no replacement path. I haven't completely analyzed everything that goes wrong downstream of that, but making it encode a tiny rectangle resolves the rendering artifacts.

It's likely that this logic worked when it was written, but the suppression of zero-length segments got more aggressive because of stroke correctness.

I think the best way to handle this is to write a special case path encoder that just pushes a single zero-length line, bypassing the logic in the general path encoder. Then, I believe the binning logic will correctly detect that the bounding box is empty, and cull the clip and everything it encloses from flowing to coarse rasterization.

**Comment by raphlinus** [comment] 2024-07-31 21:11
The current blend stack depth is 4 (and the value of `BLEND_STACK_SPLIT` can be tweaked, though setting it larger may degrade performance). However, there are optimizations in place so it's entirely possible you'll see correct or "almost correct" rendering even if that's exceeded. I wouldn't worry too much about limiting it on the client side unless you're seeing serious artifacts. If there's any evidence it's going to be a problem, I'm inclined to just fix it.

**Closed** 2024-08-12 21:14 UTC
Labels: bug
