### ISSUE TITLE
Broken SVG file panics when rendering

### ISSUE THREAD

**Issue by sirxyzzy** [linebender/vello#372] opened 2023-10-07 18:26 UTC
There is a problem with one of the resources, specifically for Coat of Arms of Poland.svg

In vellum, on windows, loading this image, through running the examples. causes a panic if paged to

I think the svg file is at fault, as if I load it in a default windows viewer I get an error message and a partial rendering

This page contains the following errors:
error on line 3897 at column 32: AttValue: ' expected

**Comment by DJMcNab** [comment] 2024-02-24 21:23
Thanks for the report, and sorry we didn't get back to you sooner. Im not able to reproduce this issue locally.

I believe the download probably failed, leaving you with a partial download. We've improved our download process to more accurately validate that the download completed as expected.

Let me know if you can still reproduce this issue after deleting the invalid file and running the download command on the latest `main`.

I'm going to close this issue, but let me know if it's still occurring for you so we can reopen and debug this.

**Closed** 2024-02-24 21:23 UTC
