### ISSUE TITLE
trying to render emojis causes system freeze

### ISSUE THREAD

**Issue by dvc94ch** [linebender/vello#142] opened 2022-01-10 12:41 UTC
hard to provide a reproducer as I've modified stuff in different places. also it would be bordering on distributing malware. any suggestions how to debug a system freeze?

**Comment by raphlinus** [comment] 2022-01-10 14:21
It's very hard to diagnose. Can you say more about what you're running it on?

I do have one place I'm seeing GPU timeouts, which is #139. I started digging into it but have put it on the back burner for now.

**Comment by dvc94ch** [comment] 2022-01-10 15:01
so made sure that the thing panics before rendering to avoid system freezes. seems like the problem is that the glyph only provides a bitmap and no outlines which isn't handled and then causes a `ctx.fill_glyph` without a glyph being encoded. Letting make_path return `None` doesn't render the emoji, but it prevents a freeze.

next question would be, how to go about rendering the bitmap?

**Comment by raphlinus** [comment] 2022-01-10 15:03
There is FillImage support in the shaders, but the CPU-side support for it is currently missing. I will add it, but no guarantees when.

**Comment by DJMcNab** [comment] 2023-02-11 14:22
Since this issue was opened, we've migrated to wgpu (in https://github.com/linebender/vello/pull/193)

I think things are likely to be different enough since then, and since no reproduction was reached, I'm going to close this out.

**Closed by DJMcNab** 2023-02-11 14:22 UTC
