### ISSUE TITLE
Vello image rendering artifacts?

### ISSUE THREAD

**Issue by StarArawn** [linebender/vello#656] opened 2024-08-05 15:41 UTC
Hello! I'm working on a nine-patch rendering system using vello image rendering:
![image](https://github.com/user-attachments/assets/abf3da6e-5716-41d9-a2e2-8ccd31bd845d)

The lines that are appearing I believe are the result of texture atlas bleeding. Although I'm not entirely convinced that is the case since the image is rasterized in compute there should be no issue with atlas bleeding as compute shaders do not have UV's and UV address modes. You can see that they(the artifacts) do not exist in the atlas that Vello produces:
![image](https://github.com/user-attachments/assets/4c023d62-4f76-411a-bdf2-62d74f5717d8)

Another possibility is that anti-aliasing is causing these artifacts. I would think it would be odd if AA ran on images though, but perhaps its an effect that runs "post render" I simply don't know enough about vello's internals.

Its also entirely possible that this issue is entirely my fault in my own code, although I am using fairly well tested(bevy code). I'll attempt to reproduce this in a MRE as soon as I am able to.

**Comment by DJMcNab** [comment] 2024-08-05 16:03
> The lines that are appearing

There are lots of lines in your image. Can you clarify to which lines you are referring?

**Comment by StarArawn** [comment] 2024-08-05 21:11
> > The lines that are appearing
> 
> There are lots of lines in your image. Can you clarify to which lines you are referring?

The black parts are meant to be completely black:
![image](https://github.com/user-attachments/assets/e0cb0da8-ff37-4b2a-95c1-78bdad6c0732)

**Comment by StarArawn** [comment] 2024-08-05 21:42
I was able to reproduce this using only vello:
![image](https://github.com/user-attachments/assets/8b9e5e23-36f4-4804-823f-7f68292bc4c6)

you can find my MRE here:
https://github.com/StarArawn/vello/commit/0c3b0dbc701f98153130a616ed8cfe56948236f4

Curiously it appears as though the scale of the image causes the issue.

**Comment by DJMcNab** [comment] 2024-09-02 11:23
I believe that the artifacts you are seeing are called conflation artifacts. I don't have a good suggested workaround, although you might be able to introduce some artificial overlap between the sections.

This is a very hard problem to solve, although we are working on it. See [#gpu>Conflation Artifact Free Compositing](https://xi.zulipchat.com/#narrow/stream/197075-gpu/topic/Conflation.20artifact.20free.20compositing).

I think we probably could close this as a duplicate of #49.

**Comment by DJMcNab** [comment] 2024-10-24 07:53
@dfrg has pointed out that I have likely mis-triaged this issue. Could you please try this with #722, which I think should fix at least some of this?

**Closed** 2024-11-08 09:36 UTC
